[package]
name = "voxl"
version = "0.0.1"
edition = "2018"
description = "An engine for voxel games"
license-file = "LICENSE"
readme = "README.md"
authors = ["Senre <jesuisutile0@gmail.com>"]
homepage = "https://github.com/voxl-rs/voxl"
repository = "https://github.com/voxl-rs/voxl.git"
documentation = "https://docs.rs/voxl"
keywords = ["game engine", "voxels", "3D"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
voxl_graph = { path = "voxl_graph", version = "0.0.1", optional = false }
voxl_time = { path = "voxl_time", version = "0.0.1", optional = false }
voxl_core = { path = "voxl_core", version = "0.0.1", optional = false }

env_logger = "0.8.1"
log = "0.4.11"

[dev-dependencies]
criterion = "0.3.3"

[build-dependencies]
shaderc = "0.6.3"
fs_extra = "1.2.0"
glob = "0.3.0"
anyhow = "1.0.33"
